{"name": "Create order with invalid ingredients", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "api_client = <helpers.api_client.APIClient object at 0x000001EC8292BA80>\n\n    @pytest.fixture\n    def registered_user(api_client):\n        user_data = {\n            'email': generate_email(),\n            'password': generate_password(),\n            'name': generate_name()\n        }\n        # Регистрация\n        response = api_client.post(Urls.REGISTER, json=user_data)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\nconftest.py:22: AssertionError"}, "start": 1755429713804, "stop": 1755429713804, "uuid": "6760289b-31a8-42c9-a057-d0dd1c9037ad", "historyId": "35c4c4f479bb1208f0fc34c58f8f1e92", "testCaseId": "35c4c4f479bb1208f0fc34c58f8f1e92", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_ingredients", "labels": [{"name": "feature", "value": "Order Creation"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "dea-1611"}, {"name": "thread", "value": "7772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}