{"name": "Login with valid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 200\n +  where 401 = <Response [401]>.status_code", "trace": "self = <test_login_user.TestLoginUser object at 0x000001EC6313BD90>, api_client = <helpers.api_client.APIClient object at 0x000001EC62ED59A0>\nregistered_user = {'email': 'qmiles@example.org', 'password': '&+ROclAl$3', 'token': ''}\n\n    @allure.title('Login with valid credentials')\n    def test_login_valid_user(self, api_client, registered_user):\n        response = api_client.post(Urls.LOGIN, json={\n            'email': registered_user['email'],\n            'password': registered_user['password']\n        })\n    \n>       assert response.status_code == 200\nE       assert 401 == 200\nE        +  where 401 = <Response [401]>.status_code\n\ntests\\test_login_user.py:16: AssertionError"}, "start": 1755429585993, "stop": 1755429586123, "uuid": "1844f289-f70a-44d1-9680-65f692bfb1c8", "historyId": "635e39da8edc9086fbdae58401159c07", "testCaseId": "635e39da8edc9086fbdae58401159c07", "fullName": "tests.test_login_user.TestLoginUser#test_login_valid_user", "labels": [{"name": "feature", "value": "User Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "dea-1611"}, {"name": "thread", "value": "12860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}