{"name": "Create order with auth and valid ingredients", "status": "broken", "statusDetails": {"message": "NameError: name 'Urls' is not defined", "trace": "self = <test_create_order.TestCreateOrder object at 0x000001EC6313B250>, api_client = <helpers.api_client.APIClient object at 0x000001EC62F1EBA0>\nregistered_user = {'email': 'marcusholmes@example.org', 'password': 'tFNL2SOa*5', 'token': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....WNkOWVkMjgwMDAxYjY3ZjA1NiIsImlhdCI6MTc1NTQyOTU4MSwiZXhwIjoxNzU1NDMwNzgxfQ.hq2x9ry8aZswAxTTwc6akQSlSZu7ylmf1dpUACTr9H8'}\n\n    @allure.title('Create order with auth and valid ingredients')\n    def test_create_order_auth_valid_ingredients(self, api_client, registered_user):\n>       ingredients = get_valid_ingredients(api_client)\n\ntests\\test_create_order.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\napi_client = <helpers.api_client.APIClient object at 0x000001EC62F1EBA0>\n\n    def get_valid_ingredients(api_client):\n>       response = api_client.get(Urls.INGREDIENTS)\nE       NameError: name 'Urls' is not defined\n\nhelpers\\data_generator.py:16: NameError"}, "start": 1755429580312, "stop": 1755429580312, "uuid": "2c05c315-04da-4232-9a36-452395426470", "historyId": "2557f520b74a9823fd48b2439dc083f1", "testCaseId": "2557f520b74a9823fd48b2439dc083f1", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_auth_valid_ingredients", "labels": [{"name": "feature", "value": "Order Creation"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "dea-1611"}, {"name": "thread", "value": "12860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}